# Generated by Django 4.2.1 on 2023-05-10 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pollingunit', '0003_localgovernment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollingUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summon', models.IntegerField()),
                ('local_govt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollingunit.localgovernment')),
            ],
        ),
    ]
